spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: taha-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    topics:
      my-topic:
        name: taha-topic
        partitions: 3
        concurrency: 3
